#!/bin/bash

# depends on npm i -g localtunnel
# $1 should be port

if [ -z "$1" ]; then
  PORT=8080
  echo "using default port 8080"
else
  PORT="$1"
fi

exec 3< <(lct -p $PORT)
read <&3 line
SERVER_URL="${line:13}"
echo "setting SERVER_URL to $SERVER_URL in export.sh"

echo "export SERVER_URL=\"$SERVER_URL\"" >> ~/config/private/export.sh